clusterName: CHANGEME
splunkObservability:
  realm: CHANGEME
  accessToken: CHANGEME

gateway:
  enabled: true
  autoscaling:
    enabled: true
  # For local development k8s clusters (1 node large), it is recommended users downsize the gateway resources
  # Default CPU Limit: 4
  # Default Memory Limit: 8Gi
  resources:
   limits:
    cpu: 1
    memory: 2Gi
agent:
  enabled: false
clusterReceiver:
  enabled: false
