kind: Deployment
metadata:
  name: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: splunk
          image: splunk/splunk:8.2.0
          ports:
            - containerPort: 8000
            - containerPort: 8088
            - containerPort: 8089
          env:
            - name: SPLUNK_START_ARGS
              value: --accept-license
            - name: SPLUNK_USER
              valueFrom:
                secretKeyRef:
                  name: splunk-secrets
                  key: splunk-user
            - name: SPLUNK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splunk-secrets
                  key: splunk-password
            - name: SPLUNK_LAUNCH_CONF
              value: OPTIMISTIC_ABOUT_FILE_LOCKING=1SER
              valueFrom:
                secretKeyRef:
                  name: splunk-secrets
                  key: splunk-user
            - name: SPLUNK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splunk-secrets
                  key: splunk-password
            - name: SPLUNK_LAUNCH_CONF
              value: OPTIMISTIC_ABOUT_FILE_LOCKING=1

---
apiVersion: v1
kind: Service
metadata:
  name: splunk-service
spec:
  type: ClusterIP
  ports:
    - name: splunk
      port: 8089
      targetPort: 8089
  selector:
    app: splunk
