version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /ci_scripts
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /functional_tests
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /test
    schedule:
      interval: daily
