splunkObservability:
  metricsEnabled: true
  tracesEnabled: false
  logsEnabled: false
  accessToken: X
  realm: us0
clusterName: X

agent:
  enabled: false
  otelcol:
    # The registry and name of the opentelemetry collector image to pull
    # repository: quay.io/signalfx/splunk-otel-collector
    repository: otel/opentelemetry-collector-contrib

clusterReceiver:
  config:
    receivers:
      k8s_cluster:
        auth_type: serviceAccount
        metadata_exporters:
        - signalfx
        metrics:
          k8s.pod.status_reason:
            enabled: true
        resource_attributes:
          k8s.container.status.last_terminated_reason:
            enabled: true
    processors:
      memory_limiter:
        check_interval: 2s
        limit_mib: 400
