{{- if .Values.operator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-webhook-service
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    component: otel-operator
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/component: otel-operator
spec:
  template:
    spec:
      containers:
        - name: wait-for-webhook
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              until nc -z {{ template "splunk-otel-collector.namespace" . }}:{{ template "splunk-otel-collector.fullname" . }}-operator-webhook 443; do
                echo "Waiting for service to be accessible...";
                sleep 1;
              done;
              echo "Operator Webhook Service is accessible."
      restartPolicy: Never
{{- end }}
