---
# Source: splunk-otel-collector/charts/cert-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: default-cert-manager
  namespace: default
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.11.0
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9402
    name: tcp-prometheus-servicemonitor
    targetPort: 9402
  selector:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: "controller"
