---
# Source: splunk-otel-collector/charts/cert-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: default-cert-manager
  namespace: default
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: default
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.11.0
