splunkObservability:
  metricsEnabled: true
  tracesEnabled: true
  logsEnabled: true
  accessToken: CHANGEME
  realm: us0
clusterName: CHANGEME
environment: CHANGEME
metricsEnabled: true
logsEnabled: false
tracesEnabled: true

operator:
  manager:
    autoInstrumentationImage:
      java:
        repository: jvsplk/splunk-otel-java
        tag: 1.0.2
