apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: splunk-instrumentation
spec:
  exporter:
    endpoint: http://$(SPLUNK_OTEL_AGENT):4317
  propagators:
    - tracecontext
    - baggage
    - b3
  env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    # - name: OTEL_RESOURCE_ATTRIBUTES
    #  value: deployment.environment=dev
