---
# Source: splunk-otel-collector/templates/secret-splunk-validation-hook.yaml
# Helm hook that validates a custom secret provided by the user has all the required fields.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-collector-validate-secret
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.82.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.82.0"
    app: splunk-otel-collector
    chart: splunk-otel-collector-0.82.0
    release: default
    heritage: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
---
# Source: splunk-otel-collector/templates/secret-splunk-validation-hook.yaml
apiVersion: v1
kind: Pod
metadata:
  name: default-splunk-otel-collector-validate-secret
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.82.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.82.0"
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  # Use a shortly lived service account here since the normal service account may not exist yet.
  # See: https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle
  serviceAccountName: splunk-collector-validate-secret
  restartPolicy: Never
  containers:
  - name: validate-secret
    image: quay.io/signalfx/splunk-otel-collector:0.82.0
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c"]
    args:
      - if [ "true" = "true" ] && [ ! -f /otel/secret/splunk_observability_access_token ]; then
          echo Splunk Observability destination is enabled, but custom\
          Kubernetes secret \"splunk-otel-collector\"\
          doesn\'t have required field \"splunk_observability_access_token\".;
          export TOKEN_INVALID=true;
        fi;
        if [ "false" = "true" ] && [ ! -f /otel/secret/splunk_platform_hec_token ]; then
          echo Splunk Platform destination is enabled, but custom Kubernetes\
          secret \"splunk-otel-collector\" doesn\'t\
          have required field \"splunk_platform_hec_token\".;
          export TOKEN_INVALID=true;
        fi;
        if [ "$TOKEN_INVALID" = "true" ]; then
          echo Please update the secret.;
          exit 1;
        fi
    volumeMounts:
      - name: secret
        mountPath: /otel/secret
        readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: splunk-otel-collector
