---
# Source: splunk-otel-collector/templates/secret-splunk-validation-service-account.yaml
# Service account that is used by validation. Only exists during pre-install or pre-upgrade phases.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-collector-validate-secret
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.82.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.82.0"
    app: splunk-otel-collector
    chart: splunk-otel-collector-0.82.0
    release: default
    heritage: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
