---
# Source: splunk-otel-collector/templates/secret-splunk-validation-service-account.yaml
# The service account and pod to run a Helm hook for validating that custom a secret provided by user has all the
# required fields.

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.82.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.82.0"
    app: splunk-otel-collector
    chart: splunk-otel-collector-0.82.0
    release: default
    heritage: Helm
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-2"
name: default-splunk-otel-collector-validate-secret
