apiVersion: v2
appVersion: 0.86.0
description: Splunk OpenTelemetry Collector for Kubernetes
icon: https://github.com/signalfx/splunk-otel-collector-chart/tree/main/splunk.png
keywords:
- splunk
- opentelemetry
- observability
- logs
- traces
- metrics
- apm
maintainers:
- name: dmitryax
- name: jvoravong
- name: emaderer
name: splunk-otel-collector
type: application
version: 0.86.11
