apiVersion: v2
name: splunk-otel-collector
version: 0.70.0
appVersion: 0.70.0
description: Splunk OpenTelemetry Collector for Kubernetes
icon: https://github.com/signalfx/splunk-otel-collector-chart/tree/main/splunk.png
type: application
keywords:
- splunk
- opentelemetry
- observability
- logs
- traces
- metrics
- apm
maintainers:
- name: dmitryax
- name: jvoravong
- name: emaderer
dependencies:
#  - name: opentelemetry-demo
#    version: 0.18.1
#    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: opentelemetry-operator
    version: 0.21.5
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
