apiVersion: v2
name: splunk-otel-collector
version: 0.72.0
appVersion: 0.72.0
description: Splunk OpenTelemetry Collector for Kubernetes
icon: https://github.com/signalfx/splunk-otel-collector-chart/tree/main/splunk.png
type: application
keywords:
- splunk
- opentelemetry
- observability
- logs
- traces
- metrics
- apm
maintainers:
- name: dmitryax
- name: jvoravong
- name: emaderer
dependencies:
  - name: cert-manager
    version: 1.11.0
    alias: certmanager
    repository: https://charts.jetstack.io
    condition: certmanager.enabled
  - name: opentelemetry-operator
    version: 0.26.0
    alias: operator
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: operator.enabled
