---
# Source: splunk-otel-collector/templates/operator/instrumentation.yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default-splunk-otel-collector
  labels:
    app.kubernetes.io/name: splunk-otel-collector
    helm.sh/chart: splunk-otel-collector-0.83.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.83.0"
    app: splunk-otel-collector
    component: otel-operator
    chart: splunk-otel-collector-0.83.0
    release: default
    heritage: Helm
    app.kubernetes.io/component: otel-operator
spec:
  exporter:
    endpoint: http://$(SPLUNK_OTEL_AGENT):4317
  propagators:
    - tracecontext
    - baggage
    - b3
  env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP

  apache-httpd:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.3
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: splunk.zc.method=autoinstrumentation-apache-httpd:1.0.3
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.0.0-rc.1
    env:
      - name: SPLUNK_PROFILER_ENABLED
        value: true
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: splunk.zc.method=autoinstrumentation-dotnet:1.0.0-rc.1
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(SPLUNK_OTEL_AGENT):4318
  go:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:0.2.2-alpha
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: splunk.zc.method=autoinstrumentation-go:0.2.2-alpha
  java:
    image: ghcr.io/signalfx/splunk-otel-java/splunk-otel-java:v1.26.0
    env:
      - name: SPLUNK_PROFILER_ENABLED
        value: true
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: environment=dev,splunk.zc.method=splunk-otel-java:v1.26.0
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.41.1
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: splunk.zc.method=autoinstrumentation-nodejs:0.41.1
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.40b0
    env:
      - name: SPLUNK_PROFILER_ENABLED
        value: true
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: splunk.zc.method=autoinstrumentation-python:0.40b0
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(SPLUNK_OTEL_AGENT):4318
