apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: splunk-instrumentation-java
spec:
  exporter:
    endpoint: http://$(SPLUNK_OTEL_AGENT):4317
  java:
    env:
      - name: SPLUNK_OTEL_AGENT
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.hostIP
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(SPLUNK_OTEL_AGENT):4317
      - name: OTEL_TRACES_EXPORTER
        value: otlp
