name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - helm-charts/**/Chart.yaml

jobs:
  maybe_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Chart.yaml Update
        id: check_update_chart
        run: |
          VERSION_DIFF=$(git diff HEAD^ -- "*Chart.yaml" | grep -E "^\+version:" || echo "")
          if [[ ! -z "$VERSION_DIFF" ]]; then
            NEW_VERSION=$(echo "$VERSION_DIFF" | awk '{print $2}')  # Extract new version
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo "New release needed, creating..."
            echo "VALID_UPDATE=1" >> $GITHUB_ENV
            cp CHANGELOG.md helm-charts/splunk-otel-collector/
            cat RELEASE.md
          else
            echo "No new release needed"
            echo "VALID_UPDATE=0" >> $GITHUB_ENV
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        if: env.VALID_UPDATE == '1'
        with:
          charts_dir: helm-charts
          config: .github/workflows/configs/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
