name: Prepare New Helm Chart Release

# Description:
# This workflow prepares a new release of the helm chart by updating chart and app versions as well as creating a PR.
# A release PR will be created in these cases.
#  - When a user kicks offs this workflow manually. A user can specify the CHART_VERSION and APP_VERSION used for the new release.
#  - When the cron schedule kicks off the job and there is a major or minor version different for the APP_VERSION. The CHART_VERSION will be automatically incremented appropriately.

on:
  schedule:
    # Run every Monday and Thursday
    - cron: "45 12 * * 1,4"
  workflow_dispatch:
    inputs:
      CHART_VERSION:
        description: 'Optionally overrides the chart version in Chart.yaml.'
        required: false
        default: ''
      APP_VERSION:
        description: 'Optionally overrides the app version in Chart.yaml.'
        required: false
        default: ''
      DEBUG:
        description: 'Enable debug mode for the script.'
        required: false
        default: 'false'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    env:
      CHART_VERSION: ${{ github.event.inputs.CHART_VERSION }}
      APP_VERSION: ${{ github.event.inputs.APP_VERSION }}
      DEBUG: ${{ github.event.inputs.DEBUG }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: make install-tools

      - name: Update Version
        id: update
        run: |
          LATEST_VER=$(curl -L -qs -H 'Accept: application/vnd.github+json' https://api.github.com/repos/signalfx/splunk-otel-collector/releases/latest | jq -r .tag_name)
          sed -i "s/appVersion:.*/appVersion: ${LATEST_VER##v}/" helm-charts/splunk-otel-collector/Chart.yaml
          make render
          echo "Latest version: ${LATEST_VER}"
          echo "LATEST_VER=${LATEST_VER}" >> "$GITHUB_OUTPUT"
          if [[ -n $(git status --short) ]];then
            echo "NEED_UPDATE=1" >> "$GITHUB_OUTPUT"
          else
            echo "NEED_UPDATE=0" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare Release
        id: prepare_release
        run: |
          make prepare-release CHART_VERSION=$CHART_VERSION APP_VERSION=$APP_VERSION CREATE_BRANCH=false DEBUG=$DEBUG

      - name: Check if PR is already open
        id: check_if_pr_open
        run: |
          DIFF=1
          git fetch origin
          ((git show-ref --verify --quiet refs/heads/${{ steps.prepare_release.outputs.BRANCH_NAME }}) || (git diff --no-ext-diff --quiet main..${{ steps.prepare_release.outputs.BRANCH_NAME }} -- helm-charts)) && DIFF=0
          echo "PR_NEEDED=$DIFF" >> "$GITHUB_OUTPUT"

      - name: Open PR for Version Update
        id: open_pr
        if: ${{ steps.prepare_release.outputs.NEED_UPDATE == 1 && steps.check_if_pr_open.outputs.PR_NEEDED == 1 }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Prepare release v${{ steps.prepare_release.outputs.LATEST_CHART_VERSION }}
          title: Prepare release v${{ steps.prepare_release.outputs.LATEST_CHART_VERSION }}
          body: |
            Description
            - Release Helm chart version ${{ steps.prepare_release.outputs.LATEST_CHART_VERSION }}
            - Includes collector version ${{ steps.prepare_release.outputs.LATEST_APP_VERSION }}
          branch: ${{ steps.prepare_release.outputs.BRANCH_NAME }} # Same branch name for all PRs
          base: main
          delete-branch: true
