name: Release Charts

on:
  push:
    branches:
      - main
    # Release only if the 'version' field in Chart.yaml was updated
    paths:
      - helm-charts/**/Chart.yaml

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Chart.yaml Update
        id: check_update_chart
        run: |
          CHART_DIFF=$(git diff HEAD^ --name-only)
          VERSION_DIFF=$(git diff HEAD^ -- Chart.yaml | grep -E "^\+version:")
          if [[ "$CHART_DIFF" == "helm-charts/**/Chart.yaml" && "$VERSION_DIFF" != "" ]]; then
            echo "::set-output name=VALID_UPDATE::true"
          else
            echo "::set-output name=VALID_UPDATE::false"
          fi

  create_release:
    needs: check_release
    runs-on: ubuntu-latest
    if: ${{ needs.check_release.outputs.VALID_UPDATE == 'true' }}
    steps:
      - name: Configure Git
        run: git config user.name "$GITHUB_ACTOR" && git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.3

      - name: Set up chart dependencies
        run: make render

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: helm-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
