name: Check for new chart dependency updates

on:
  schedule:
    # This cron job is scheduled to run at minute 45 past every 12th hour.
    - cron: "45 */12 * * *"
  workflow_dispatch:

env:
  CHART_YAML: helm-charts/splunk-otel-collector/Chart.yaml
  LATEST_API: https://api.github.com/repos/{repo}/releases/latest

jobs:
  maybe_update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['cert-manager', 'opentelemetry-operator'] # Add other repos here
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Update Chart
        id: update_chart
        run: |
          DEP_PATH=$(yq e '.dependencies[] | select(.name == "${{ matrix.repo }}")' $CHART_YAML -j | jq -r '.version')
          LATEST_VER=$(curl -qs -H "Accept: application/vnd.github+json" $(echo $LATEST_API | sed "s/{repo}/${{ matrix.repo }}/g") | jq -r .tag_name)
          echo "LATEST_VER=$LATEST_VER" >> $GITHUB_OUTPUT
          echo "Current version of ${{ matrix.repo }} is $DEP_PATH, latest is $LATEST_VER"
          if [ "$LATEST_VER" == "$DEP_PATH" ]; then
            echo We are already up to date. Nothing else to do.
          else
            echo 'Looks like we need to update...'
            echo Updating to new version in chart.yaml
            echo "NEED_UPDATE=1" >> $GITHUB_OUTPUT
            yq e -i ".dependencies[] |= if .name == \"${{ matrix.dependency }}\" then .version = \"$LATEST_VER\" | @yaml else . end" $CHART_YAML
            echo "Current git diff:"
            git --no-pager diff
          fi
      - name: PR the new version
        if: ${{ steps.update_chart.outputs.NEED_UPDATE == 1 }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update ${{ matrix.repo }} chart version
          title: Update ${{ matrix.repo }} chart version to ${{ steps.update_chart.outputs.LATEST_VER }}
          body: Use the new version of the ${{ matrix.repo }} chart
          branch: "update-${{ matrix.repo }}-${{ steps.update_chart.outputs.LATEST_VER }}"
          base: main
          delete-branch: true
          modify-outputs: false
