name: Check for new instrumentation versions

# Description:
# This workflow is responsible for checking for new versions of Splunk instrumentation libraries
# used in operator-based auto-instrumentation and updating the values.yaml if necessary.

on:
  schedule:
    # Run every 12th hour at minute 45 past.
    - cron: "45 */12 * * *"
  workflow_dispatch:
    inputs:
      DEBUG_MODE:
        description: 'Enable debug mode'
        required: false
        default: 'false'

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate GitHub Workflow Matrix
        id: generate_matrix
        run: |
          matrix=$(./ci_scripts/update-instrumentation-dependencies.sh generate_github_workflow_matrix)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  update-images:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define a dynamic matrix based on the output of the generate_matrix job
        include: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
    steps:
      - name: Run Update for ${{ matrix.language }}
        run: |
          path="${{ matrix.path }}"
          repository="${{ matrix.repository }}"
          current_tag="${{ matrix.current_tag }}"
          latest_tag="${{ matrix.latest_tag }}"
          tag_line="${{ matrix.tag_line }}"

          echo "Updating Splunk Operator Instrumentation for $path"
          # Set debug argument if DEBUG_MODE is true
          DEBUG_ARG=""
          if [ "${{ github.event.inputs.DEBUG_MODE }}" == "true" ]; then
            DEBUG_ARG="--debug"
          fi

          # Run the update script and handle errors
          # Emits output env vars NEED_UPDATE, TAG_LOCAL, and TAG_UPSTREAM
          ./ci_scripts/update-images-operator-splunk.sh "$path" $DEBUG_ARG || exit 1

          # Check if an update is needed
          if [ "$NEED_UPDATE" -eq 0 ]; then
            echo "No updates detected for $path. Exiting."
            exit 0
          fi

          echo "Rendering chart template..."
          make render

          echo "Displaying current git diff..."
          git --no-pager diff

      - name: Set Git Config
        if: ${{ steps.update-images.outputs.NEED_UPDATE == 1 }}
        run: |
          # Set global Git config for author and committer
          ./ci_scripts/base_util.sh setup_git

      - name: PR the new version
        if: ${{ steps.update-images.outputs.NEED_UPDATE == 1 }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update ${{ matrix.language }} instrumentation version
          title: Bump ${{ matrix.language }} from ${{ steps.update-images.outputs.TAG_LOCAL }} to ${{ steps.update-images.outputs.TAG_UPSTREAM }} in ${{ env.VALUES_YAML }}
          body: Use the latest version of ${{ matrix.language }}
          branch: "update-${{ matrix.language }}" # Same branch name for all PRs
          base: main
          delete-branch: true
          modify-outputs: false
