name: Check for new instrumentation versions

# Description:
# This workflow is responsible for checking for new versions of Splunk instrumentation libraries
# used in operator based auto-instrumentation and updating the values.yaml if necessary.

on:
  schedule:
    # Run every 12th hour at minute 45 past.
    - cron: "45 */12 * * *"
  workflow_dispatch:
    inputs:
      DEBUG_MODE:
        description: 'Enable debug mode'
        required: false
        default: 'false'

env:
  VALUES_YAML: helm-charts/splunk-otel-collector/values.yaml
  LATEST_API: https://api.github.com/repos/signalfx/splunk-otel-{lang}/releases/latest

jobs:
  maybe_update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add docker images that require version updates here
        include:
          - name: 'java'
            yaml_file_path: 'helm-charts/splunk-otel-collector/values.yaml'
            yaml_value_path: 'operator.instrumentation.spec.java'
          - name: 'nodejs'
            yaml_file_path: 'helm-charts/splunk-otel-collector/values.yaml'
            yaml_value_path: 'operator.instrumentation.spec.nodejs'
          - name: 'network-explorer'
            yaml_file_path: 'helm-charts/splunk-otel-collector/values.yaml'
            yaml_value_path: 'networkExplorer.images'
          - name: 'fluentd-hec'
            yaml_file_path: 'helm-charts/splunk-otel-collector/values.yaml'
            yaml_value_path: 'image.fluentd'
          - name: 'splunk-ci'
            yaml_file_path: 'ci_scripts/k8s-splunk.yml'
            yaml_value_path: 'spec.containers[0].image'
    steps:
      - uses: actions/checkout@v4

      - name: Update Version
        id: swizzle_version
        run: |
          echo "Update Splunk Operator Instrumentation for ${{ matrix.name }}"

          # Set debug argument if DEBUG_MODE is true
          DEBUG_ARG=""
          if [ "${{ github.event.inputs.DEBUG_MODE }}" == "true" ]; then
            DEBUG_ARG="--debug"
          fi

          # Run the update script and handle errors
          # Emits output env vars swizzle_version.outputs.TAG_LOCAL and steps.swizzle_version.outputs.TAG_UPSTREAM
          ./ci_scripts/update-images-operator-splunk.sh ${{ matrix.yaml_file_path }} ${{ matrix.yaml_value_path }} $DEBUG_ARG || exit 1

          # Check if an update is needed
          if [ "$NEED_UPDATE" -eq 0 ]; then
            echo "No updates detected. Exiting."
            exit 0
          fi

          echo "Displaying current git diff..."
          git --no-pager diff

      - name: PR the new version
        id: swizzle_pr
        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update ${{ matrix.name }} instrumentation version
          title: Bump ${{ matrix.name }} from ${{ steps.swizzle_version.outputs.TAG_LOCAL }} to ${{ steps.swizzle_version.outputs.TAG_UPSTREAM }} in ${{ matrix.yaml_file_path }}
          body: Use the latest version of ${{ matrix.name }}
          branch: "update-${{ matrix.name }}" # Same branch name for all PRs
          base: main
          delete-branch: true
          modify-outputs: false

      - name: Render Chart Examples
        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
        run: |
          echo "Rendering chart template..."
          ./ci_scripts/update-images-operator-splunk.sh ${{ matrix.yaml_file_path }} ${{ matrix.yaml_value_path }} || exit 1
          make render || exit 1

      - name: Create Changelog
        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
        run: |
          make chlog-new FILENAME="update-${{ matrix.name }}" CHANGE_TYPE=enhancement COMPONENT=operator NOTE="Bump ${{ matrix.name }} to ${{ steps.swizzle_version.outputs.TAG_UPSTREAM }} in ${{ env.VALUES_YAML }}" ISSUES=[${{ steps.swizzle_pr.outputs.pull-request-number }}] || exit 1

      - name: Update PR with changelog
        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update ${{ matrix.name }} instrumentation version
          title: Bump ${{ matrix.name }} from ${{ steps.swizzle_version.outputs.TAG_LOCAL }} to ${{ steps.swizzle_version.outputs.TAG_UPSTREAM }} in ${{ matrix.yaml_file_path }}
          body: Use the latest version of ${{ matrix.name }}
          branch: "update-${{ matrix.name }}" # Same branch name for all PRs
          base: main
          delete-branch: true
          modify-outputs: false
