name: Check for new chart release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  CHART_YAML: helm-charts/splunk-otel-collector/Chart.yaml
  REPO_URL: https://github.com/signalfx/splunk-otel-collector

jobs:
  auto_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Update Chart Version
        id: update_chart_version
        run: |
          # Fetch the latest version from the GitHub repository
          LATEST_TAG=$(curl -sL $REPO_URL/releases/latest | awk -F 'tag/' '{print $2}' | awk -F '"' '{print $1}')
          LATEST_APP_VER=$(echo $LATEST_TAG | awk -F '.' '{print substr($1, 2)"."$2}')

          # Retrieve the current version from chart.yaml
          CURRENT_VERSION=$(yq eval '.version' $CHART_YAML)
          CURRENT_APP_VERSION=$(yq eval '.appVersion' $CHART_YAML)

          echo "Current version is $CURRENT_VERSION, latest appVersion is $LATEST_APP_VER"

          # Check if major or minor version update has occurred
          if [[ "$LATEST_APP_VER" != "$CURRENT_APP_VERSION" && ("$LATEST_APP_VER" == "$CURRENT_APP_VERSION"* || "$LATEST_APP_VER" == "$CURRENT_APP_VERSION."*) ]]; then
            echo "Updating appVersion in Chart.yaml"
            echo "NEED_UPDATE=1" >> $GITHUB_ENV
            yq eval ".appVersion = \"$LATEST_APP_VER\"" $CHART_YAML > temp_chart.yaml && mv temp_chart.yaml $CHART_YAML
          else
            echo "No major or minor version update detected. Skipping the update."
          fi
      - name: PR the new version
        if: env.NEED_UPDATE == '1'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update chart version
          title: Update chart version to ${{ steps.update_chart_version.outputs.LATEST_APP_VER }}
          body: |
            Update the appVersion in the Chart.yaml file to ${{ steps.update_chart_version.outputs.LATEST_APP_VER }}.
            This will reflect the latest version from the repository.
          branch: "update-chart-version-${{ steps.update_chart_version.outputs.LATEST_APP_VER }}"
          base: main
          draft: true
