name: Check for new instrumentation versions

# Description:
# This workflow is responsible for checking for new versions of Splunk instrumentation libraries
# used in operator based auto-instrumentation and updating the values.yaml if necessary.

on:
  schedule:
    # Run every 12th hour at minute 45 past.
    - cron: "45 */12 * * *"
  workflow_dispatch:
    inputs:
      DEBUG_MODE:
        description: 'Enable debug mode'
        required: false
        default: 'false'

env:
  VALUES_YAML: helm-charts/splunk-otel-collector/values.yaml
  LATEST_API: https://api.github.com/repos/signalfx/splunk-otel-{lang}/releases/latest
  DEBUG_MODE: ${{ github.event.inputs.DEBUG_MODE }}

jobs:
  maybe_update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add languages that require version updates here
        language: ['java']
    steps:
      - uses: actions/checkout@v4

      - name: Update Version
        id: swizzle_version
        run: |
          echo "Update Splunk Operator Instrumentation for ${{ matrix.language }}"

          # Run the update script and handle errors
          ./ci_scripts/update-images-operator-splunk.sh ${{ matrix.language }} || exit 1

          # Check if an update is needed
          if [ "$NEED_UPDATE" -eq 0 ]; then
            echo "No updates detected. Exiting."
            exit 0
          fi

          echo "Rendering chart template..."
          make render

          echo "Displaying current git diff..."
          git --no-pager diff
      - name: PR the new version
        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update ${{ matrix.language }} instrumentation version
          title: Update ${{ matrix.language }} instrumentation version to ${{ steps.swizzle_version.outputs.TAG_UPSTREAM }}
          body: Use the new version of the ${{ matrix.language }} instrumentation
          branch: "update-${{ matrix.language }}"
          base: main
          delete-branch: true
      - name: Add CHANGELOG entry
        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
        run: |
          git fetch origin
          git checkout "update-${{ matrix.language }}"
          RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository }}:update-${{ matrix.language }})
            echo "$RESPONSE"
          PR_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository }}:update-${{ matrix.language }} \
                | jq '.[0].number')
          make chlog-new CHANGE_TYPE=enhancement COMPONENT=operator \
            NOTE="Update ${{ matrix.language }} instrumentation version to ${{ steps.swizzle_version.outputs.TAG_UPSTREAM }}" \
            ISSUES="[$PR_ID]"
          git add .
          git commit -m "Add .chloggen entry"
          git push origin "update-${{ matrix.language }}"
