name: Check for new Helm chart dependency versions

on:
  schedule:
    # This cron job is scheduled to run at minute 45 past every 4th hour.
    - cron: "45 */4 * * *"
  workflow_dispatch:

env:
  CHART_YAML: helm-charts/splunk-otel-collector/chart.yaml

jobs:
  maybe_update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency: ['cert-manager', 'opentelemetry-operator'] # Add other dependencies here
        repo: ['jetstack', 'open-telemetry'] # Corresponding GitHub organizations
    steps:
      - uses: actions/checkout@v3.5.3
      - name: swizzle version
        id: swizzle_version
        run: |
          LATEST_API=https://api.github.com/repos/${{ matrix.repo }}/${{ matrix.dependency }}/releases/latest
          LOCAL_VER=$(yq e ".dependencies[] | select(.name == \"${{ matrix.dependency }}\") | .version" $CHART_YAML)
          LATEST_VER=$(curl -qs -H "Accept: application/vnd.github+json" $LATEST_API | jq -r .tag_name)
          echo "LATEST_VER=$LATEST_VER" >> $GITHUB_OUTPUT
          echo "Current version of ${{ matrix.dependency }} is $LOCAL_VER, latest is $LATEST_VER"
          if [ "$LATEST_VER" == "$LOCAL_VER" ]; then
            echo We are already up to date. Nothing else to do.
          else
            echo 'Updating to new version in chart.yaml'
            echo "NEED_UPDATE=1" >> $GITHUB_OUTPUT
            yq e -i '.dependencies[] |= if .name == "'"${{ matrix.dependency }} "'" then .version = env.LATEST_VER | @yaml else . end' $CHART_YAML
            echo "Current git diff:"
            git --no-pager diff
          fi
      - name: PR the new version
        if: ${{ steps.swizzle_version.outputs.NEED_UPDATE == 1 }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update ${{ matrix.dependency }} version
          title: Update ${{ matrix.dependency }} version to ${{ steps.swizzle_version.outputs.LATEST_VER }}
          body: Use the new version of the ${{ matrix.dependency }}
          branch: "update-${{ matrix.dependency }}-${{ steps.swizzle_version.outputs.LATEST_VER }}"
          base: main
          delete-branch: true
          modify-outputs: false
