name: Ensure valid and up-to-date Changelog

on: pull_request

jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Install chloggen
        run: go install go.opentelemetry.io/build-tools/chloggen@latest

      - name: Run make chlog-validate
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
        run: make chlog-validate

      - name: Read current version of the Chart
        id: read-chart
        uses: cumulusds/get-yaml-paths-action@v1
        with:
          file: helm-charts/splunk-otel-collector/Chart.yaml
          version: version

      - name: Ensure that CHANGELOG.md has an entry for the current version
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.read-chart.outputs.version }}
          path: ./CHANGELOG.md
